# Generated by Django 3.2.18 on 2023-03-14 17:36

import cloudinary.models
import django.contrib.postgres.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_postgallery'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postgallery',
            options={'ordering': ['-created_on']},
        ),
        migrations.AlterField(
            model_name='postgallery',
            name='images',
            field=django.contrib.postgres.fields.ArrayField(base_field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='images'), blank=True, default=list, size=None),
        ),
        migrations.AlterField(
            model_name='postgallery',
            name='title_image',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='Title_image'),
        ),
    ]
