# Generated by Django 3.2.18 on 2023-03-14 17:51

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20230314_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postgallery',
            name='images',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='images'),
        ),
    ]
