# Generated by Django 3.2.18 on 2023-03-14 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_postgallery_images'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postgallery',
            options={},
        ),
    ]
