# Generated by Django 3.2.18 on 2023-03-26 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_postproducts'),
    ]

    operations = [
        migrations.AddField(
            model_name='postproducts',
            name='excerpt',
            field=models.TextField(blank=True),
        ),
    ]
