# Generated by Django 3.2.18 on 2023-04-01 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_postproducts_excerpt'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookAParty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('party_theme', models.CharField(choices=[('JU', 'Jungle'), ('UN', 'Unicorn'), ('ME', 'Mermaid'), ('LI', 'Little ladies'), ('GA', 'Gamers'), ('TI', 'Tik Tok'), ('SO', 'Soccer')], max_length=2)),
                ('balloons', models.BooleanField(default=False)),
                ('bouncy_castle', models.BooleanField(default=False)),
                ('kids_age', models.CharField(choices=[('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14')], max_length=2)),
                ('number_of_teepees', models.CharField(choices=[('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7')], max_length=2)),
                ('street', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=50)),
                ('county', models.CharField(max_length=50)),
                ('eircode', models.CharField(max_length=10)),
                ('date', models.DateField()),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Published')], default=0)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
    ]
