# Generated by Django 3.2.18 on 2023-04-02 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_bookaparty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookaparty',
            name='slug',
        ),
        migrations.AddField(
            model_name='bookaparty',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bookaparty',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='bookaparty',
            name='order_nr',
            field=models.SlugField(default='new_order', editable=False, max_length=200, unique=True),
        ),
    ]
