# Generated by Django 3.2.18 on 2023-04-02 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20230402_0910'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookaparty',
            name='additional_info',
            field=models.TextField(default='You can add some additional information or ask us a question here.'),
        ),
    ]
