# Generated by Django 3.2.18 on 2023-04-15 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_bookaparty_host'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookaparty',
            name='additional_info',
            field=models.TextField(default='Ask us a question here.'),
        ),
    ]
